	<style>
	  #login{
	        background: rgba(30,127,0,0.73);
	        display: none;
	        position: fixed;
	        right: 0;
	        top: 20.5%;
	        right: 13.7%;
	        width: 205px;
	        padding: 25px;
	        z-index: 2000000;
	        border-radius: 5px;

	    }
	    #login label{
	        margin-top: 10px;
	        font-family: Lucida Calligraphy;
	        font-size: 20px;
	        color: white;
	    }

	    #login input, #bd{

	        height: 30px;
	        width: 200px;
	        border-radius: 5px !important;
	        border: 1px solid #c4b8a6;
	        -webkit-transition: border 0.4s linear;
	    }

	    #login input:focus{
	        border: 1px solid indigo;
	        border-radius: 5px;
	    }

	    #btnLogin{
	        font-family: Century Gothic;
	        font-size: 15px;
	        width: 100px;
	        margin-top: 20px !important;

	        background: -webkit-radila-gradient(center, circle ,green 0%,rgba(122,255,200,0.9) 150%);
	    }
	</style>

