
	<!-- end: META -->
	<!-- start: MAIN CSS -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url();?>public/assets/plugins/select2/select2.css" />

	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/iCheck/skins/all.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/animate.css/animate.min.css">
	<!-- end: MAIN CSS -->
	<!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/summernote/dist/summernote.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/toastr/toastr.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-select/bootstrap-select.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/DataTables/media/css/DT_bootstrap.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
	<!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
	<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/weather-icons/css/weather-icons.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/nvd3/nv.d3.min.css">
	<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
	<!-- start: CORE CSS -->
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/styles.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/styles-responsive.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/plugins.css">	
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/plugins1.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/themes/theme-style8.css" type="text/css" id="skin_color">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/print.css" type="text/css" media="print"/>
	<!-- end: CORE CSS -->
	<link rel="shortcut icon" href="favicon.ico" />
 <link href="<?php echo base_url();?>public/assets/plugins/sweetalert/lib/sweet-alert.css" rel="stylesheet" />
