
		<script src="<?php echo base_url();?>public/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
		<!--<![endif]-->
		<script src="<?php echo base_url();?>public/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/iCheck/jquery.icheck.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/moment/min/moment.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootbox/bootbox.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jquery.appear/jquery.appear.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/velocity/jquery.velocity.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
		<!-- end: MAIN JAVASCRIPTS -->
		<!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
		<script src="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/toastr/toastr.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>

		<script src="<?php echo base_url();?>public/assets/plugins/truncate/jquery.truncate.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/summernote/dist/summernote.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/jquery.steps.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/jquery.steps.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/subview.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/subview-examples.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
		<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/nvd3/lib/d3.v3.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/nvd3/nv.d3.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/nvd3/src/models/historicalBar.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/nvd3/src/models/historicalBarChart.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/nvd3/src/models/stackedArea.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/nvd3/src/models/stackedAreaChart.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/jquery.sparkline/jquery.sparkline.js"></script>
		<script src="<?php echo base_url();?>public/assets/plugins/easy-pie-chart/dist/jquery.easypiechart.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/index.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<!-- start: CORE JAVASCRIPTS  -->
		<script src="<?php echo base_url();?>public/assets/js/main.js"></script>
		<!-- end: CORE JAVASCRIPTS  -->
		<script type="text/javascript" src="<?php echo base_url();?>public/assets/plugins/select2/select2.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/table-data.js"></script>
		<script src="<?php echo base_url();?>public/js/bootstrap-combobox.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/ui-notifications.js"></script>
   		<script src="<?php echo base_url();?>public/assets/plugins/sweetalert/lib/sweet-alert.min.js"></script>
		<script src="<?php echo base_url();?>public/assets/js/ui-animations.js"></script>


		<script>
			jQuery(document).ready(function() {
				Main.init();
				// SVExamples.init();
				TableData.init();
				Index.init();
				UINotifications.init();
				Animation.init();
			});
		</script>
		<script>
	        $(function()
	        {
	           $(".combobox").combobox();
	        })
	    </script>
