
	<script type="text/javascript" src="<?php echo base_url(); ?>public/js/jquery-1.6.js" ></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>public/js/cufon-yui.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>public/js/cufon-replace.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>public/js/Didact_Gothic_400.font.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>public/js/Shanti_400.font.js"></script>
	<script src="<?php echo base_url(); ?>public/js/roundabout.js" type="text/javascript"></script>
	<script src="<?php echo base_url(); ?>public/js/roundabout_shapes.js" type="text/javascript"></script>
	<script src="<?php echo base_url(); ?>public/js/jquery.easing.1.2.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>public/js/script.js"></script>

	<script src="<?php echo base_url(); ?>public/js/jquery-latest.min.js"></script>

	<!-- Incluimos el plugin -->
	<script src="<?php echo base_url(); ?>public/js/bjqs.min.js"></script>
	<script src="<?php echo base_url(); ?>public/js/script2.js"></script>


	<!-- librerias para animaciones -->
	<script src="<?php echo base_url(); ?>public/js/jquery.min.js"></script>
	<script src="<?php echo base_url(); ?>public/js/jquery-ui.min.js"></script>
	<script src="<?php echo base_url(); ?>public/js/smoothscroll.min.js"></script>
	<script src="<?php echo base_url(); ?>public/js/appear.min.js"></script>
	<script src="<?php echo base_url(); ?>public/js/animations.js"></script>
	<script src="<?php echo base_url(); ?>public/js/backbone.js"></script>


	<!-- galeria de fotos -->

	<script src="<?php echo base_url(); ?>public/js/main.js"></script>

	<script>
		$(document).ready(function(){
	              $("#candado").click(function(){
	                 $("#login").slideToggle("fast");
	              });
	            });
	</script>